
#### THEME ####
general.import = [
  "~/.config/alacritty/vesper.toml"
]

##### GENERAL #####
[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14.0

[font.normal]
family = "Geist Mono"
style = "Regular"

[font.bold]
family = "Geist Mono"
style = "Bold"

[font.italic]
family = "Geist Mono"
style = "Italic"

[font.bold_italic]
family = "Geist Mono"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

