# --- Vesper Theme Colors ---
set -g status-position top
set -g status-justify left
set -g status-style "bg=#101010 fg=#A0A0A0"
set -g status-interval 1

set -g status-left "#[fg=#FFC799,bold] #S #[fg=#5C5C5C]│ "
set -g status-left-length 20
set -g status-right "#[fg=#A0A0A0]%-I:%M %p "
set -g status-right-length 50

setw -g window-status-format "#[fg=#5C5C5C] #I #W "
setw -g window-status-current-format "#[fg=#FFFFFF,bold] #I #W "
setw -g window-status-separator ""

set -g pane-border-lines simple
set -g pane-border-style "fg=#282828"
set -g pane-active-border-style "fg=#FFC799"

set -g message-style "bg=#232323 fg=#FFFFFF"
set -g message-command-style "bg=#232323 fg=#FFFFFF"
setw -g mode-style "bg=#232323 fg=#FFFFFF"
setw -g clock-mode-colour "#FFC799"
