id = "nginx"
name = "Nginx"
version = "0.0.1"
schema_version = 1
description = "Nginx support"
repository = "https://github.com/d1y/nginx-zed"
authors = ["d1y <chenhonzhou@gmail.com>"]
themes = []
languages = ["languages/nginx"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.nginx]
repository = "https://gitlab.com/joncoole/tree-sitter-nginx"
rev = "b4b61db443602b69410ab469c122c01b1e685aa0"

[language_servers.nginx]
language = "Nginx"
languages = []

[language_servers.nginx.language_ids]
