id = "tsgo"
name = "tsgo"
version = "0.0.1"
schema_version = 1
description = "Native implementation of TypeScript compiler."
repository = "https://github.com/zed-extensions/tsgo"
authors = ["Zed Industries <hello@zed.dev>"]
themes = []
icon_themes = []
languages = []
capabilities = []

[lib]
kind = "Rust"
version = "0.5.0"

[grammars]

[language_servers.tsgo]
languages = ["TypeScript", "TSX", "JavaScript", "JSX"]

[language_servers.tsgo.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
